### PR TITLE
should allow user control phone number format

### PR DESCRIPTION
**Pull request by itrethan**

### CODE REVIEW

**Comment by layerssss** [comment]
Good point. thanks!

**Comment by itrethan** [comment]
Can you please make a new release on the npm?

**Comment by layerssss** [comment]
@itrethan Sorry for the late of arrival :shipit: ✨  https://github.com/layerssss/Faker-zh-cn.js/releases/tag/0.5.9

**Comment by itrethan** [comment]
@layerssss Thanks, but npm still has 0.5.8 as the latest.

**Comment by layerssss** [comment]
Sorry, i forgot the `npm publish`, now it should be there.

**Pull request merged**
